(define (fib n)
  (cond ((= n 0) 0)
        ((= n 1) 1)
        (else (+ (fib (- n 1)) (fib (- n 2))))
  )
)

(define (fib n)
  (define (fib-iter a b count)
    (if (= count 0)
      b
      (fib-iter (+ a b) a (- count 1))
    )
  )
  (fib-iter 1 0 n)
)

(display (fib 0)) (display " ")
(display (fib 1)) (display " ")
(display (fib 2)) (display " ")
(display (fib 3)) (display " ")
(display (fib 4)) (display " ")
(display (fib 5)) (display " ")
